### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by ghost** [bakd247/hashAdder#2]
Hi dear I have a few question,

1. For one key how many time will be for finding?
2. When will be ready final release?

Best Regards,

**Comment by bakd247** [comment]
There is no guarantee a key will ever be found….
it could be found in 2 seconds or it could take till the end of time…
I am currently working a full time ojb so it wont be until around June until the final release is ready

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: Thursday, April 27, 2023 5:24 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [bakd247/hashAdder] Few questions (Issue #2)


Hi dear I have a few question,

  1.  For one key how many time will be for finding?
  2.  When will be ready final release?

Best Regards,

**Comment by Juventino96** [comment]
Hi dear I understand but after your tests how much is success rate?

**Comment by bakd247** [comment]
So far…not much…because the current version doesn’t support large multiple and divisor lists and only does multiples and divisors of 2….also is only a single core process….
I worte it to just show the proof of concept and I can show it recover a key very fast…I just havnt finished the video yet because I am trying to update the current version to be at least faster, support multi process and cover obvious/ easy to count to spots first…
however because the algorithm is using randomness it is much more likely to find a key than to not using this method over brute force…(on the current version as well as the upcoming version)
I am writing the newer version to include larger multiples and divisors lists and support multiple keys as well as multiprocessing…
it’s the multi-process thing that I am actually working on at the moment….
I currently am searching for 6 keys for separate clients at the moment so I am highly incentivized to finish asap…
just doing what I can when I can…
I will keep you posted on updates and let you know when I am done with the video that explains it in more detail sooner than later


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by bakd247** [comment]
This is only a "academic break" of the ecdsa Algorithm...it has not recovered any keys yet but is can easily be shown that it works using any key that you know already and using its multiples and halves to show that it in fact finds the correct private key by finding a modular multiple of that key
