### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by moedacompix** [bakd247/hashAdder#5]
Sorry for the question, but have you had any results and can it be implemented for GPU?

**Comment by bakd247** [comment]
at the moment it would only recover very unsecure keys at a fast rate...of your key is truly random then it has a very low chance of finding it because the current version is using random 256 bit integers as sample keys. Once I finish the next update which will have "easyCount" enabled...this will evenly divide the search space and narrow down everything making sure that no key is tried twice....this will guarantee a lot faster recovery times.
 I am working on getting it working with multiprocessing and multi threading on a cpu first...then I intend on implementing it on GPUs...the data structures are different for gpus so the code will be a lot more complex.
I am also currently working on a video that explains everything that is going on when it is run.
The methods i am using basically make recovering a keys worst case scenario much smaller. Once the "easyCount" is done...this should enable a "best case scenario" due to how modular multiplication and division works
