### ISSUE TITLE
v2 version

### ISSUE THREAD

**Issue by agoora** [bakd247/hashAdder#7]
Hi,
When would the v2 version be ready?
(multithreading, multiprocessing, writeing collision lists to a file , maybe GPU version).
Thanks.

**Comment by bakd247** [comment]
I am not quite sure at the moment...I have been working on it a little bit at a time each day. At the moment I am concentrating on making the collision list larger by saving it to disk as well as multithreading and multicore processing to allow for much faster search times per random iteration. I would say at the latest...new years...or earlier...I should have version 2 done.
The plan after that is to allow for multiple keys and then gpu....
I kind of have to make multithreading work on a cpu in order to be able to scale it with gpus...and because of memory limitations....I may have to make the gpus version use both the cpu and gpu together to avoid bottlenecks.
Currently the main limitations on this version is memory capacity for collision list size and memory speed and cpu single core performance speed for each calculation and binary search operation.
I am scripting a video at this very moment and it will explain all this in much greater detail....look for the video (in the description, which i have rewritten as well, of version 1.4) some time this month for certain.
